inherit_gem:
  prettier: rubocop.yml
require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance
  - rubocop-capybara

AllCops:
  Exclude:
    - Gemfile*
    - bin/*
    - gemfiles/**/*
    - vendor/bundle/**/*
    - docker/**/*
  # Automatically enables new cops so that we only have to add them to
  # edit default behavior
  NewCops: enable

Rails:
  Enabled: true

Style/NumericLiterals:
  Exclude:
    - db/schema.rb

# We don't care about method length, since we check method cyclomatic complexity.
Metrics/ClassLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Layout/LineLength:
  Enabled: false

Naming/FileName:
  Exclude: ["devise-security.gemspec"]

Rails/DuplicateAssociation:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false

Style/NegatedIf:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/SymbolArray:
  EnforcedStyle: brackets

# Trailing commas make for clearer diffs because the last line won't appear
# to have been changed, as it would if it lacked a comma and had one added.
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

# Cop supports --auto-correct.
# Configuration parameters: PreferredDelimiters.
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    # Using `[]` for string arrays instead of `()`, since normal arrays are
    # indicated with `[]` not `()`.
    "%w": "[]"
    "%W": "[]"

Style/AndOr:
  # Whether `and` and `or` are banned only in conditionals (conditionals)
  # or completely (always).
  # They read better, more like normal English.
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/HashSyntax:
  EnforcedShorthandSyntax: either

# No one cares for these
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
  SafeAutoCorrect: false
Style/ClassAndModuleChildren:
  Enabled: false

Metrics/AbcSize:
  CountRepeatedAttributes: false
  Max: 22
  Exclude:
    - db/migrate/**/*.rb # mostly create table blocks
    - db/migrate/*.rb # mostly create table blocks

Style/RedundantReturn:
  Enabled: false

Lint/UnusedMethodArgument:
  Enabled: false
