---
include:
  - "**/*.rb"
exclude:
  - spec/**/*
  - test/**/*
  - vendor/**/*
  - ".bundle/**/*"
  - docker/**/*
require:
  - actioncable
  - actionmailer
  - actionpack
  - actionview
  - activejob
  - activemodel
  - activerecord
  - activestorage
  - activesupport
domains: []
reporters:
  - rubocop
  - require_not_found
# plugins:
#   - solargraph-arc # Need solargraph ~> 0.44.2 https://github.com/alisnic/solargraph-arc
require_paths: []
max_files: 5000
