version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - autofetch
  - datetime
  - Meslo
  - omniauth
  - omniauthable
  - plpgsql
  - postgres
  - rubocop
  - sassc
  - sendfile
  - sqltools
  - Sysnative
  - timeoutable
  - uuid
  - validatable
  - windir
ignoreWords: []
import: []
language: en,pt,pt-BR
enableFiletypes:
  - ruby
