version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - omniauth
  - postgres
  - rubocop
  - sqltools
ignoreWords: []
import: []
language: en,pt,pt-BR
enableFiletypes:
  - ruby
