ARG RUBY_VERSION=3.2.2-alpine3.18
FROM ruby:${RUBY_VERSION}

### Define ENV Variables
ENV APP_ROOT /kodoverdikto
ENV PATH $APP_ROOT/bin:$PATH

### Configure bundler
ENV BUNDLE_PATH /usr/local/bundle
ENV GEM_PATH $BUNDLE_PATH
ENV BUNDLE_BIN $BUNDLE_PATH
ENV PATH $BUNDLE_PATH/bin:$BUNDLE_PATH/gems/bin:$PATH
ARG BUNDLER_VERSION=2.4.6

# Define container workdir location
WORKDIR $APP_ROOT

# Install system dependencies required both at runtime and build time
# tzdata (https://tips.tutorialhorizon.com/2017/08/29/tzinfodatasourcenotfound-when-using-alpine-with-docker/)
# shared-mime-info -- Dependency from gem 'mimemagic' (https://github.com/mimemagicrb/mimemagic#dependencies)
RUN apk add --update --no-cache --virtual run-dependencies \
    git \
    gnupg \
    libaio \
    libpq-dev \
    postgresql14-client \
    shared-mime-info \
    sqlite-dev \
    tzdata

### Configure bundler for development (Don`t copy gemfiles and install only bundler, as the gems will the installed afterward on container run and cached locally)
# build-dependencies can NOT be deleted after gems instalation to optimize image size because they may still be needed as gems are installed dinamically
# Some gems need build, example 'bcrypt', 'json', 'jaro_winkler' --> (dependency of development gem 'solargraph')
RUN apk add --update --no-cache --virtual build-dependencies make g++ build-base  && \
    gem update --system && \
    gem install bundler -v $BUNDLER_VERSION --verbose && \
    bundle config set deployment 'false' && \
    bundle config set jobs 20

###### DEV ONLY
# Install packages usefull for development
# util-linux install whereis package that is useful to debug bin paths
# less is needed by pry gem https://github.com/pry/pry/issues/1248#issuecomment-767676627)
# opensssh adds ssh to Devcontainer (DEV ONLY for pull and push with ssh key)
RUN apk add --update --no-cache --virtual dev-dependencies \
    util-linux \
    less  \
    openssh

# [Optional] Set the default user. Omit if you want to keep the default as root.
# https://aka.ms/vscode-remote/containers/non-root#_change-the-uidgid-of-an-existing-container-user
ARG USERNAME=root
ARG USER_UID=1000
ARG USER_GID=$USER_UID
RUN apk add --update --no-cache shadow
RUN if [[ "$USERNAME" != "root" ]] ; then \
    groupadd --gid $USER_GID $USERNAME \
    && useradd --uid $USER_UID --gid $USER_GID -m $USERNAME ; \
    else echo "Running with $USERNAME user" ; \
    fi
USER $USERNAME

### Define app version
ARG COMMIT_HASH=untagged
ENV COMMIT_HASH=${COMMIT_HASH}

# Open port 80 for HTTP access
EXPOSE 80
# Open port 443 and 8443 for HTTPS access
# EXPOSE 443 8443

# Start Process
ENTRYPOINT [ "/kodoverdikto/scripts/entrypoints/web-create.sh" ]
CMD [ "/kodoverdikto/scripts/entrypoints/web-start.sh" ]
