#!/bin/bash
set -e

if [ "$DATABASE_USER" ]; then
  echo """
    CREATE USER $DATABASE_USER WITH ENCRYPTED PASSWORD '$DATABASE_PASSWORD';
    CREATE DATABASE $DATABASE_DB;
    GRANT ALL PRIVILEGES ON DATABASE $DATABASE_DB TO $DATABASE_USER;
    ALTER DATABASE $DATABASE_DB OWNER TO $DATABASE_USER;
    ALTER ROLE $DATABASE_USER WITH CREATEDB;
    --ALTER ROLE $DATABASE_USER WITH SUPERUSER;
  """ | psql -v ON_ERROR_STOP=1 -U "$POSTGRES_USER" -d "$POSTGRES_DB"
fi

if [ "$TEST_DATABASE_USER" ]; then
  echo """
    CREATE USER $TEST_DATABASE_USER WITH ENCRYPTED PASSWORD '$TEST_DATABASE_PASSWORD';
    CREATE DATABASE $TEST_DATABASE_DB;
    GRANT ALL PRIVILEGES ON DATABASE $TEST_DATABASE_DB TO $TEST_DATABASE_USER;
    ALTER DATABASE $TEST_DATABASE_DB OWNER TO $TEST_DATABASE_USER;
    ALTER ROLE $TEST_DATABASE_USER WITH CREATEDB;
  """ | psql -v ON_ERROR_STOP=1 -U "$POSTGRES_USER" -d "$POSTGRES_DB"
fi