default: &default
  adapter: <%= ENV.fetch("DB_ADAPTER") {"postgresql"} %>
  host: <%= ENV.fetch("DB_HOST") {"localhost"} %>
  port: <%= ENV.fetch("DB_PORT") {5432} %>
  database: <%= ENV.fetch("DB_NAME") {"postgres"} %>
  username: <%= ENV.fetch("DB_USER") {"postgres"} %>
  password: <%= ENV.fetch("DB_PSWD") {"postgres"} %>
  statement_limit: 150

development:
  <<: *default

homolog:
  <<: *default

production:
  <<: *default
  pool: <%= ENV.fetch("DB_POOL") {5} %>

test:
  adapter: <%= ENV.fetch("TEST_DB_ADAPTER") {"postgresql"} %>
  host: <%= ENV.fetch("TEST_DB_HOST") {"localhost"} %>
  port: <%= ENV.fetch("TEST_DB_PORT") {5432} %>
  database: <%= ENV.fetch("TEST_DB_NAME") {"postgres"} %>
  username: <%= ENV.fetch("TEST_DB_USER") {"postgres"} %><%= ENV.fetch("TEST_ENV_NUMBER") {""} %>
  password: <%= ENV.fetch("TEST_DB_PSWD") {"postgres"} %>
  statement_limit: 150
